[[xrt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d4b13286cdd5d7210af7b656c8587b0118097a37"
libc = "glibc"
os = "linux"

    [[xrt.download]]
    sha256 = "584341c6b145c7417d197fd9ead894bc60b13c7d4f7c4ac347a2be96b1991b40"
    url = "https://github.com/DO6LTM/xrt_jll.jl/releases/download/xrt-v2.17.0+2/xrt.v2.17.0.x86_64-linux-gnu-cxx03.tar.gz"
[[xrt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2b8e75d8aee68c69d3886f620e9210d79f4030a"
libc = "glibc"
os = "linux"

    [[xrt.download]]
    sha256 = "b896fe1073fb5c2dd31cec84e7c4c15bcbc2444ddefd3a7fa4824f64bb6eac2f"
    url = "https://github.com/DO6LTM/xrt_jll.jl/releases/download/xrt-v2.17.0+2/xrt.v2.17.0.x86_64-linux-gnu-cxx11.tar.gz"
[[xrt]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7bbb3db58db4bc38bb2016b69c6788fca16ff062"
os = "windows"

    [[xrt.download]]
    sha256 = "b69c31a989de68a88a0f72dfef23fb1fc35d566cdcd077198dd8c8d0b11f6d0a"
    url = "https://github.com/DO6LTM/xrt_jll.jl/releases/download/xrt-v2.17.0+2/xrt.v2.17.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[xrt]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7f6074ec0dfc09d15af1d6e411539d17bab3397"
os = "windows"

    [[xrt.download]]
    sha256 = "686bbacd38866b21a4bde91d8fe42cd4ff1d81b18e606a6da71bc12af31b7f51"
    url = "https://github.com/DO6LTM/xrt_jll.jl/releases/download/xrt-v2.17.0+2/xrt.v2.17.0.x86_64-w64-mingw32-cxx11.tar.gz"
